hosts:
    - <%= host %>

# No multisite.
multisite: No

# Extensions
extensions:
<% extensions.forEach(function (extension) { -%>
  - <%= extension %>
<% }) -%>

# PHP Version
php: <%= phpVersion %>

# Database details
database:
    name: wordpress
    user: wordpress
    password: vagrantpassword
    prefix: wp_
